services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DEV_DATABASE_URL=postgres://postgres:postgres@db:5432/todos
      - TEST_DATABASE_URL=postgres://postgres:postgres@db:5432/todos_test
    ports:
      - "8008:8008"
volumes:
  db-data:
